
export const RAW_LIST_STRING = `
TOTAL: 236 cards - $1,547.30 (3 cards missing price)
1 Ugin, the Ineffable (JP Alternate Art) [WAR]
1 Tamiyo, Collector of Tales (JP Alternate Art) [WAR]
1 Nissa, Who Shakes the World (JP Alternate Art) [WAR]
4 Rally the Ancestors [FRF]
1 Rally the Ancestors [PRE]
1 Kenrith, the Returned King [BABP]
1 Shielded by Faith [SS2]
1 Runed Stalactite [LRW]
2 Leyline of Sanctity [M20]
1 Wrath of God [C13]
1 Sun Titan [DDL]
1 Soulfire Grand Master [FRF]
1 Shalai, Voice of Plenty [DOM]
1 All That Glitters [ELD]
1 Sram, Senior Edificer [AER]
1 Idyllic Tutor [THB]
1 Karmic Guide [C13]
1 Sevinne's Reclamation [C19]
1 Ghostly Prison [C19]
3 Collector Ouphe [MH1]
3 Whisperwood Elemental [FRF]
1 Zendikar Resurgent [OGW]
2 Zendikar Resurgent [OGW]
1 Kytheon, Hero of Akros [ORI]
1 Gilded Goose [ELD]
1 Gemrazer (Showcase) [IKO]
2 Once Upon a Time [ELD]
1 Gemrazer [IKO]
1 Gilded Goose [ELD]
1 Fauna Shaman [UMA]
1 Greater Good [BBD]
1 Steel Leaf Champion [GAME]
1 Quirion Ranger [VIS]
1 Tempt with Discovery [C16]
1 Elvish Piper [A25]
1 Pir, Imaginative Rascal [BBD]
1 Wicked Wolf (Extended Art) [ELD]
1 Guardian Project [RNA]
1 Whiptongue Hydra [C18]
1 Pelt Collector [GRN]
1 Weather the Storm [MH1]
1 Rishkar's Expertise [AER]
1 Chameleon Colossus [V13]
1 The Great Henge [ELD]
1 Voracious Hydra [M20]
1 Nissa, Voice of Zendikar [OGW]
1 Elemental Bond [ORI]
1 Oath of Nissa [OGW]
1 Parallel Lives [ISD]
1 Acidic Slime [FNM]
1 Polukranos, World Eater [DDL]
1 Vorinclex, Voice of Hunger [NPH]
1 Steelbane Hydra [ELD]
1 Genesis Wave [SOM]
1 Dosan the Falling Leaf [CHK]
1 God-Eternal Rhonas [WAR]
1 Reki, the History of Kamigawa [SOK]
1 Seedborn Muse [BBD]
1 Polluted Delta [KTK]
1 Okina, Temple to the Grandfathers [CHK]
1 Canopy Vista [BFZ]
1 Preordain [DDI]
2 Preordain [M11]
1 Dig Through Time [UMA]
2 Emry, Lurker of the Loch [ELD]
1 Dig Through Time [KTK]
1 Babygodzilla, Ruin Reborn - Pollywog Symbiote [IKO]
1 Babygodzilla, Ruin Reborn - Pollywog Symbiote [IKO]
1 Thassa, Deep-Dwelling [THB]
1 Thassa, God of the Sea [THS]
1 Flash [A25]
1 Master of Waves [DDT]
1 Agent of Treachery [M20]
1 Supreme Will [HOU]
1 Hidden Strings [DGM]
1 Master of the Pearl Trident [DDT]
1 Teferi, Mage of Zhalfir [IMA]
1 Retract [DST]
1 Cryptic Command [IMA]
1 Thassa's Oracle (Extended Art) [THB]
1 Laboratory Maniac [UMA]
1 Shark Typhoon [IKO]
1 Sea-Dasher Octopus (Showcase) [IKO]
1 Mystical Dispute [ELD]
1 Inventors' Fair [KLD]
1 Sulfur Falls [DOM]
3 Woodland Cemetery [DOM]
1 Hall of Heliod's Generosity [MH1]
1 Stomping Ground [RNA]
4 Murderous Rider [ELD]
2 Spacegodzilla, Death Corona - Void Beckoner [IKO]
2 Gutterbones [RNA]
2 Bolas's Citadel [WAR]
1 Crux of Fate [FRF]
1 Bridge from Below [UMA]
1 Kokusho, the Evening Star [IMA]
1 Vindictive Lich [C17]
1 Crumbling Ashes [EVE]
1 Revel in Riches [XLN]
1 Exhume [GRV]
1 Soul Snuffers [EVE]
1 Chainer's Edict [V13]
1 Legion's End [M20]
1 Ob Nixilis, Unshackled [M15]
1 Plague Engineer [MH1]
1 Reanimate [UMA]
1 Decree of Pain [C17]
1 Kalitas, Traitor of Ghet [OGW]
1 Kindred Dominance [C17]
1 Morphic Pool [BBD]
1 Watery Grave [GRN]
1 Snow-Covered Island [MH1]
1 Thespian's Stage [UMA]
1 Bonecrusher Giant (Showcase) [ELD]
2 Bonecrusher Giant (Showcase) [ELD]
3 Bonecrusher Giant [ELD]
2 Wild Slash [FRF]
1 Destoroyah, Perfect Lifeform - Everquill Phoenix [IKO]
2 Dreadhorde Arcanist [PRE]
2 Burning Inquiry [M10]
1 Legion Warboss [GRN]
1 Goblin Rabblemaster [DDT]
1 Magus of the Moon [IMA]
1 Alesha, Who Smiles at Death [PRE]
1 Vexing Devil [UMA]
4 Spirebluff Canal [KLD]
2 Mutavault [M14]
1 Spire Garden [BBD]
1 Flagstones of Trokair [UMA]
1 Kor Haven [NMS]
1 Glimmervoid [MRD]
1 Shivan Reef [DDU]
1 Cascade Bluffs [A25]
1 Isolated Chapel [DOM]
1 Thousand-Year Elixir [LRW]
1 Akroma's Memorial [M13]
1 Helm of the Host [DOM]
1 Blood Crypt [RNA]
1 Savai Triome [IKO]
1 Reliquary Tower [M13]
1 Temple Garden [GRN]
1 Goblin Charbelcher [DDT]
1 Brokkos, Apex of Forever (Showcase) [IKO]
1 Vadrok, Apex of Thunder [IKO]
1 Unsettled Mariner [MH1]
1 Sword of Body and Mind [SOM]
1 Stonecoil Serpent [ELD]
1 Sword of Sinew and Steel [MH1]
1 Altar of the Brood [KTK]
1 Mishra's Bauble [MB1]
1 Grim Monolith - 1999 Kai Budde (ULG) [WCD]
1 Metalworker - 2000 Jon Finkel (UDS) [WCD]
1 Mystic Forge [M20]
1 Aetherflux Reservoir [KLD]
1 Strionic Resonator [A25]
2 Chromatic Lantern [GRN]
1 Helm of the Gods [ORI]
1 Thantis, the Warweaver [C18]
1 Sidar Kondo of Jamuraa [C16]
1 Siege Rhino [KTK]
1 Maelstrom Pulse [UMA]
1 Abrupt Decay [GR1]
1 Aura Shards [CMD]
1 Twinning Staff [C20]
1 Solemn Simulacrum [C19]
1 Nicol Bolas, Dragon-God [WAR]
1 Nicol Bolas [A25]
1 March of the Multitudes [GRN]
1 Ice-Fang Coatl [MH1]
1 Windgrace's Judgment [C18]
1 Garruk, Cursed Huntsman [ELD]
1 Slitherwisp (Extended Art) [IKO]
1 Titans' Nest (Extended Art) [IKO]
1 Edric, Spymaster of Trest [CMD]
1 Lazav, Dimir Mastermind [GTC]
1 Lazav, the Multifarious [GRN]
1 The Gitrog Monster [SOI]
2 Deputy of Detention [RNA]
1 Detention Sphere [RTR]
1 Deputy of Detention [PRE]
1 Gyrus, Waker of Corpses [C18]
1 Inalla, Archmage Ritualist [C17]
1 Rielle, the Everwise (Extended Art) [IKO]
1 Notion Thief [A25]
1 Ludevic, Necro-Alchemist [C16]
1 Fallen Shinobi [MH1]
1 Xantcha, Sleeper Agent [C18]
1 Lightning Skelemental [MH1]
1 Kraum, Ludevic's Opus [C16]
1 Rakdos, the Showstopper [PRE]
1 Rakdos, Lord of Riots [GK2]
1 Dreadbore [GK2]
1 Korvold, Fae-Cursed King [ELD]
1 Supreme Verdict [RTR]
1 Karametra, God of Harvests [BNG]
1 Nethroi, Apex of Death (Showcase) [IKO]
1 Forest - Selesnya (A09) [LARP]
1 Obosh, the Preypiercer (Extended Art) [IKO]
1 Yorion, Sky Nomad (Extended Art) [IKO]
1 Privileged Position [GR1]
1 Klothys, God of Destiny [THB]
1 Pernicious Deed [A25]
1 Lord Windgrace [C18]
1 Sigarda, Host of Herons [AVR]
`